#!/usr/bin/env python3
"""Regenerate yam_linear_4310_gravity.xml: the arm + linear_4310 gripper inertial model used for gravity compensation.

lab42's YamRobotNode (market42) builds its gravity model with i2rt's combine_arm_and_gripper_xml(YAM, LINEAR_4310),
so the ~0.7 kg gripper (0.553 kg body + 2 x 0.071 kg tips) is compensated. robot_configs/yam/xdof_hq/*.yaml point at
the arm-only yam.xml (link_6 mass 1e-6) instead, which under-compensates joints 2-4 by 2-3 Nm in the packing poses.
This script splices the gripper in with the i2rt version vendored here, strips meshes/geoms (inertials are explicit,
so the torques are unchanged and the file loads without STL assets) and checks the result against the arm-only model.

    cd /nfs_us_2/karim/robots_realtime && .venv/bin/python robot_configs/yam/xdof_hq_v8dj_recorded/make_gravity_model.py
"""
from __future__ import annotations

import os
import sys
import xml.etree.ElementTree as ET

import numpy as np
from i2rt.robots.utils import GRIPPER_LINEAR_4310_PATH, I2RT_ROOT, combine_arm_and_gripper_xml
from i2rt.utils.mujoco_utils import MuJoCoKDL

HERE = os.path.dirname(os.path.abspath(__file__))
ARM_XML = os.path.join(I2RT_ROOT, "robot_models/arm/yam/yam.xml")
OUT = os.path.join(HERE, "yam_linear_4310_gravity.xml")
STARTUP = {  # motor order, arm joints only (the us05 session startup poses)
    "left": [0.018, 1.519, 0.249, 1.167, -0.170, -0.096],
    "right": [0.047, 1.497, 0.238, 1.157, 0.171, 0.031],
}


def gravity(path: str, q: list[float]) -> np.ndarray:
    z = np.zeros(6)
    return MuJoCoKDL(path).compute_inverse_dynamics(np.asarray(q, float), z, z).copy()


def main() -> None:
    combined = combine_arm_and_gripper_xml(ARM_XML, GRIPPER_LINEAR_4310_PATH)  # /tmp, absolute mesh paths
    root = ET.parse(combined).getroot()
    for asset in root.findall("asset"):
        root.remove(asset)
    for parent in root.iter():
        for geom in [c for c in parent if c.tag == "geom"]:
            parent.remove(geom)
    root.insert(0, ET.Comment(
        " GENERATED by make_gravity_model.py — do not edit. yam.xml (arm) + gripper/linear_4310/linear_4310.xml spliced by "
        "i2rt.robots.utils.combine_arm_and_gripper_xml, meshes/geoms removed (explicit inertials => identical gravity "
        "torques). Same physical model as lab42 market42's YamRobotNode (matches to <0.04 Nm at the us05 poses). "))
    ET.indent(root)
    ET.ElementTree(root).write(OUT, encoding="unicode")
    print(f"wrote {OUT}")

    kdl = MuJoCoKDL(OUT)
    print(f"model: nq={kdl.model.nq} moving mass={kdl.model.body_mass.sum():.3f} kg "
          f"(arm-only {MuJoCoKDL(ARM_XML).model.body_mass.sum():.3f} kg)")
    ok = True
    for side, q in STARTUP.items():
        t_full, t_strip, t_arm = gravity(combined, q), gravity(OUT, q), gravity(ARM_XML, q)
        ok &= bool(np.allclose(t_full, t_strip, atol=1e-6))
        print(f"{side:5s} startup  g(arm+gripper) {np.round(t_strip, 2)}  g(arm only) {np.round(t_arm, 2)}  "
              f"delta x1.3 {np.round(1.3 * (t_strip - t_arm), 2)} Nm")
    if not ok:
        sys.exit("stripped model torques differ from the meshed combined model")
    print("OK: stripped model == combined model")


if __name__ == "__main__":
    main()
